SELECT MAX(repository_size) as size, repository_url, repository_name as name, repository_owner as owner
 FROM [githubarchive:github.timeline] 
 WHERE (created_at CONTAINS "2013-06-12") 
 GROUP BY repository_url, name, owner
 ORDER BY size 
 DESC LIMIT 200
